//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalAppointmentScheduler.Core.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedicalSchedulerDBEntities : DbContext
    {
        public MedicalSchedulerDBEntities()
            : base("name=MedicalSchedulerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<L_State> L_State { get; set; }
        public virtual DbSet<L_User_Roles> L_User_Roles { get; set; }
        public virtual DbSet<User_Address> User_Address { get; set; }
        public virtual DbSet<User_Details> User_Details { get; set; }
        public virtual DbSet<User_Login> User_Login { get; set; }
    }
}
