
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MedicalAppointmentScheduler.Core.Data
{

using System;
    using System.Collections.Generic;
    
public partial class Patient
{

    public int PatientID { get; set; }

    public string Gender { get; set; }

    public int HeightFeet { get; set; }

    public int HeightInches { get; set; }

    public double Weight { get; set; }



    public virtual UserDetails User_Details { get; set; }

}

}
