//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalAppointmentScheduler.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Address
    {
        public int AddressID { get; set; }
        public string AddressLine { get; set; }
        public string City { get; set; }
        public Nullable<int> StateID { get; set; }
        public string ZipCode { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual L_State L_State { get; set; }
        public virtual User_Details User_Details { get; set; }
    }
}
