//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalAppointmentScheduler.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogin
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    
        public virtual UserDetails User_Details { get; set; }
    }
}
